[colors]
head = "cyan"
unit = "green"
user = "blue"
user_root = "red"
group = "yellow"
pid = "purple"
cpu = "yellow"
mem = "green"
vmem = "green"
rss = "green"
state = "cyan"
state_running = "green"
state_sleeping = "yellow"
state_zombie = "red"
state_stopped = "red"
state_trace_stop = "red"
state_dead = "red"
state_wakekill = "red"
state_waking = "yellow"
state_idle = "yellow"
state_locked = "yellow"
